### ISSUE TITLE
Extending reads in bamCoverage?

### ISSUE THREAD

**Issue by AliciaSchep** [lamortenera/bamsignals#16]
For single end data, is there a way for reads to be extended?  I.e. if you know that fragments are expected to be 200 bp, can you extend the reads to be that length when computing coverage?  Such extensions are common practice when analyzing ChIP-seq data. Thanks!

**Comment by lamortenera** [comment]
Hi Alicia,
Unfortunately there is not such a function in Bamsignals. The alternative
(used by several chip-seq tools, among which ChromHMM, EpiCSeg and
NucHunter) is to shift your reads by half of the fragment length (in your
case 100bp) and count only the 5' end (the bamCount function with shift
option). If you want something that looks like coverage, you can then
smooth your signal with a running mean.

I hope this helps.
Cheers
Alessandro
On 7 Jul 2016 9:42 pm, "Alicia Schep" <notifications@github.com> wrote:

For single end data, is there a way for reads to be extended? I.e. if you
know that fragments are expected to be 200 bp, can you extend the reads to
be that length when computing coverage? Such extensions are common practice
when analyzing ChIP-seq data. Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/lamortenera/bamsignals/issues/16>, or mute the thread
<https://github.com/notifications/unsubscribe/AAUAU6GjtzBjV6t3bktz326UVpM81tIMks5qTWTDgaJpZM4JHetm>
.

**Comment by AliciaSchep** [comment]
Thanks for your prompt reply!  The bamProfile with shift then post-hoc smoothing seems like a great workaround for the read extension.

**Comment by your-highness** [comment]
Hi @AliciaSchep and @lamortenera ,

having an argument for `bamCoverage()` that enables for computing coverage with an estimated fragment length is indeed a feature we thought about.

For now, you might use the following workaround for a coverage with a 200bp estimated fragment length (similar to @lamortenera 's suggestion):
```r
bamCoverageFrags <- function(bampath, gr, fragLength=200, ss = TRUE, ...) {
  prf <- bamProfile(bampath, gr, binsize=1, ss = TRUE, ...)
  cov <- lapply(as.list(prf), function(p) {
    l <- dim(p)[2]
    x1 <- cumsum(as.numeric(p[1,]))
    y1 <- c(rep(0, fragLength), x1[1:(l-200)])
    x2 <- cumsum(as.numeric(rev(p[2,])))
    y2 <- c(rep(0, fragLength), x2[1:(l-200)])
    matrix(c(x1-y1, rev(x2-y2)), ncol = l, byrow = T,
           dimnames = list(c("sense", "antisense"), NULL))
  })
  if (ss == TRUE) {
    prf@signals <- cov
  } else {
    prf@signals <- lapply(cov, colSums)
  }
  invisible(prf)
}
```

**Comment by AliciaSchep** [comment]
Awesome, thanks for the code example!

**Comment by your-highness** [comment]
As a follow up, @lamortenera : 

Should we make this option available for bamCoverage for the next release? I think the above solution would be valid to put into `./R/wrappers.R#bamCoverage`. What do you think?

**Comment by lamortenera** [comment]
It is a good workaround, but it still feels like a workaround. If you had
to describe what the output of the 'bamCoverageFrags' function is, you
would say that:

for each basepair we count the number of 5' ends falling up to x bp left
and right the actual position for the forward strand and the reverse strand
respectively, apart from the first x basepairs, where this count is off.

I think this is a messy definition that would scare users compared to

read coverage after shifting the reads of x/2 basepairs from the 5' to 3'
direction.

I would rather do some C++ work for adding a shift argument to the
bamCoverage function, if I had time.

It will still work very well for Alicia Shep, so thanks a lot for providing
this code

Cheers,
Alessandro

PS If I understand the code correctly sometimes you use the variable
'fragLength' and sometimes you hardcode '200', which might lead to problems
when 'fragLength != 200'.

**Comment by your-highness** [comment]
You are correct. There are some special cases one has to consider. I second that extending the `Coverager` in `./src/bamsignals.cpp` is a better solution.

According the hardcoded 200: I fixed this in the comment above.

**Comment by your-highness** [comment]
Closing at wontfix as a work around is supplied and no further response received
