### ISSUE TITLE
not opening bamfiles for which path contains symlinks

### ISSUE THREAD

**Issue by AliciaSchep** [lamortenera/bamsignals#17]
I have noticed that when I try running bamCoverage on bam paths that include symbolic links the function is not able to open them; when I give the full path it opens them just fine.  The paths with the symbolic links work with functions from other packages just fine.  It is easy to work around this by first converting the files to full paths, but I thought I'd bring it up anyways in case you weren't aware of this issue as it may or may not be a general issue

**Comment by your-highness** [comment]
Hi @AliciaSchep ,

With 9534f51d65666fa36f17995935f65c16c890aea3 (bamsignals v1.3) this problem was fixed in October last year. Which version of "bamsignals" are you using? Try `packageVersion("bamsignals")` 

The current version is 1.5.3. Try installing this version from Bioconductor Development
```r
source("https://bioconductor.org/biocLite.R")
useDevel()
biocLite("bamsignals")
```
or github via devtools
```r
install.packages("devtools")
devtools::install_github("lamortenera/bamsignals")
```

**Comment by AliciaSchep** [comment]
I was in fact using an old version (1.2.1) as I had installed from the non-development version of Bioconductor; I will try out the development version. Good to know that this issue is fixed.  Thanks!
