### ISSUE TITLE
Exclusion of fragments with read pairs having supplementary alignments

### ISSUE THREAD

**Issue by pkerbs** [lamortenera/bamsignals#23]
Hello,
I am interested in counting fragments (RNA-seq) that overlap a certain region.
Also I would like to exclude fragments which have supplementary alignments reported for any of its read pairs (since those are putatively chimeric reads).

As far as I understood it, `bamCoverage(bampath, gr, paired.end="extend", filteredFlag=2048, tlenFilter=NULL)` could help me here.
Unfortunately, the reads that have supplementary alignments are still counted (I guess, since they are marked as primary alignment).
Would it be possible to exclude those reads from counting, e.g. by filtering them out based on their "Hidden Tag: SA"?
Thanks in advance.

**Comment by your-highness** [comment]
Dear @pkerbs ,

Sorry for the late response :-/

You are right the logic of the filtering is done at the alignment entry level, _i.e._ supplementary alignments will be filtered out but primary alignments of those reads won't be filtered.

As a work around (dependent on your mapper) you can utilize `mapq` because reads with supplementary alignments get `0 PHRED` (in bwa and bwa-mem2). _Can you please try that?_

Best

**Comment by pkerbs** [comment]
Dear Johannes,
thank you for this hint, but I have to use STAR. It would be nice to have the option for selecting reads to count based on their hidden tags.
Best,
Paul

**Comment by your-highness** [comment]
Closing as no further response received
