### ISSUE TITLE
deal with ranges not present in the bam file

### ISSUE THREAD

**Issue by lamortenera** [lamortenera/bamsignals#4]
As Wolfgang pointed out, it can happen that a GRanges object contains chrY but the bamfile doesn't, and this would create an error. Maybe a better behaviour is to issue a warning and return a zero signal...

**Comment by your-highness** [comment]
That is a good point! We should check compatibility of GRanges and the bam file. We could deal with that in a dedicated function in R/wrappers.R that retrieves the "RNAMEs" from the index file. Often, the "RNAMEs" are shortened to numbers only, s.t. "chr" prefix is missing. Either the user has to know this in advance or we come up with a technique for notifying him. Then he can adapt his GRanges object to the bam "RNAME" notation.

I disagree on returning a zero signal for GRanges not present in the bam file because usually chrY is left out for the sake of comparison of libraries. It does not mean that there would be no reads mapping chrY.

@lamortenera Can you deal with that in your s4 branch?

**Comment by lamortenera** [comment]
This is already provided by the Rsamtools package.
Just type:
seqinfo(BamFile(bampath))
